### ISSUE TITLE
使用ali2115.txt以后emby就不能播放视频了

### ISSUE THREAD

**Issue by stiffme** [DDS-Derek/xiaoya-alist#165]
使用小雅web也能播放。
不使用ali2115.txt，也能播放。
```bash
2024-07-24 23:26:33.098 Info HttpClient: GET http://xiaoya.host:5678/d/每日更新/电视剧/国产剧/天行健/06.mkv
2024-07-24 23:26:33.474 Error Server: Error processing request
        *** Error Report ***
        Version: 4.8.8.0
        Command line: /system/EmbyServer.dll -programdata /config -ffdetect /bin/ffdetect -ffmpeg /bin/ffmpeg -ffprobe /bin/ffprobe -restartexitcode 3
        Operating system: Linux version 4.4.302+ (root@build5) (gcc version 12.2.0 (GCC) ) #69057 SMP Fri Jan 12 17:02:28 CST 2024
        Framework: .NET 6.0.25
        OS/Process: x64/x64
        Runtime: system/System.Private.CoreLib.dll
        Processor count: 4
        Data path: /config
        Application path: /system
        MediaBrowser.Model.Net.HttpException: MediaBrowser.Model.Net.HttpException: Forbidden
           at Emby.Server.Implementations.HttpClientManager.CoreHttpClientManager.SendAsyncInternal(HttpRequestOptions options, String httpMethod)
           at Emby.Server.Implementations.HttpClientManager.CoreHttpClientManager.SendAsync(HttpRequestOptions options, String httpMethod)
           at Emby.Server.Implementations.HttpServer.HttpResultFactory.GetContent(StaticFileResultOptions options, Int64 offset, Int64 length, CancellationToken cancellationToken)
           at Emby.Server.Implementations.HttpServer.FileWriter.SetContentResponseHeaders(Nullable`1 reportedTotalContentLength, CancellationToken cancellationToken)
           at Emby.Server.Implementations.HttpServer.HttpResultFactory.GetStaticResult(IRequest requestContext, StaticResultOptions options)
           at Emby.Server.MediaEncoding.Api.Progressive.BaseProgressiveStreamingService.ProcessRequest(StreamRequest request, Boolean isHeadRequest)
           at Emby.Server.Implementations.Services.ServiceController.GetTaskResult(Task task)
           at Emby.Server.Implementations.Services.ServiceHandler.ProcessRequestAsync(HttpListenerHost httpHost, IServerApplicationHost appHost, IRequest httpReq, IResponse httpRes, IStreamHelper streamHelper, RestPath restPath, String responseContentType, CancellationToken cancellationToken)
           at Emby.Server.Implementations.HttpServer.HttpListenerHost.RequestHandler(IRequest httpReq, ReadOnlyMemory`1 urlString, ReadOnlyMemory`1 localPath, CancellationToken cancellationToken)
        Source: Emby.Server.Implementations
        TargetSite: Void MoveNext()
```

同时我试过上面的URL，结果是正确的：
```bash
curl http://xiaoya.host:5678/d/每日更新/电视剧/国产剧/天行健/06.mkv -v
> GET /d/%e6%af%8f%e6%97%a5%e6%9b%b4%e6%96%b0/%e7%94%b5%e8%a7%86%e5%89%a7/%e5%9b%bd%e4%ba%a7%e5%89%a7/%e5%a4%a9%e8%a1%8c%e5%81%a5/06.mkv HTTP/1.1
> Host: xiaoya.host:5678
> User-Agent: curl/7.86.0
> Accept: */*
> 
< HTTP/1.1 302 Found
< Server: nginx
< Date: Wed, 24 Jul 2024 15:28:29 GMT
< Content-Type: text/html; charset=utf-8
< Content-Length: 281
< Connection: keep-alive
< Cache-Control: max-age=0, no-cache, no-store, must-revalidate
< Expires: Wed, 24 Jul 2024 15:42:29 GMT
< Location: https://cdnfhnfile.115.com/663d7872v=1&dl=1
< Referrer-Policy: no-referrer
< 
<a href="https://cdnfhnfile.115.com/663d78000&amp;uc=10&amp;v=1&amp;dl=1">Found</a>.
```
似乎emby不能跳转到115的直连？

**Comment by dawnsummit** [comment]
好像夸克，115的emby都不能播放。直链确实可以用potplayer打开。

**Comment by stiffme** [comment]
夸克的我可以用emby播放，似乎就是ali转存的115不行

**Comment by zhsama** [comment]
> 夸克的我可以用emby播放，似乎就是ali转存的115不行

quark可以播，阿里转115确实不行，alist直链到pot player是正常的

**Comment by stiffme** [comment]
我测试下来，似乎转存到115以后给的直连有问题，有时候会被115 cdn拒绝回复403.

**Comment by dawnsummit** [comment]
> 我测试下来，似乎转存到115以后给的直连有问题，有时候会被115 cdn拒绝回复403.
> 
> 比如
> 
> ```shell
> 文件:  all_jf.mp4   新增下载直链:  https://cn-beijing-data.aliyundrive.net/S3vy3esI%2F2012363630%2F660ac40681dbadc5b86042b684c4f11567e4b706%2F660ac40687b852898bed4405a049b0844f2fd5d5?callback=eyJjYWxsYmFja1VybCI6Im
> 07-25-2024 17:13:27  已成功缓存了 2 个文件
> 获取到115下载新链接： https://cdnfhnfile.115.com/665e0f9382080a63adbd3077f6ff82913b196575/all_jf.mp4?t=1723606337&u=64970009&s=524288000&d=vip-9sy-1&c=2&f=1&k=aa440a83d72e773fea1872a630e11b43&us=5242880000&uc=10&v=1
> 重新获取115已有文件新链接： https://cdnfhnfile.115.com/665e0f9382080a63adbd3077f6ff82913b196575/all_jf.mp4?t=1723606337&u=64970009&s=524288000&d=vip-9y-1&c=2&f=1&k=aa440a83d72e773fea1872a630e11b43&us=5242880000&uc=10&v=1
> 重新获取115已有文件新链接： https://cdnfhnfile.115.com/665e0f9382080a63adbd3077f6ff82913b196575/all_jf.mp4?t=1723606337&u=64970009&s=524288000&d=vip-97y-1&c=2&f=1&k=aa440a83d72e773fea1872a630e11b43&us=5242880000&uc=10&v=1
> [66a217376b9db926d4334e3aba172244e0cfeede]
> ```
> 
> 然后我手工curl这个拦截会被403拒绝：
> 
> ```shell
> curl 'https://cdnfhnfile.115.com/660&uc=10&v=1' -v
> * TLSv1.0 (OUT), TLS header, Certificate Status (22):
> * TLSv1.3 (OUT), TLS handshake, Client hello (1):
> * TLSv1.2 (IN), TLS header, Certificate Status (22):
> * TLSv1.3 (IN), TLS handshake, Server hello (2):
> * TLSv1.2 (IN), TLS header, Certificate Status (22):
> * TLSv1.2 (IN), TLS handshake, Certificate (11):
> * TLSv1.2 (IN), TLS header, Certificate Status (22):
> * TLSv1.2 (IN), TLS handshake, Server key exchange (12):
> * TLSv1.2 (IN), TLS header, Certificate Status (22):
> * TLSv1.2 (IN), TLS handshake, Server finished (14):
> * TLSv1.2 (OUT), TLS header, Certificate Status (22):
> * TLSv1.2 (OUT), TLS handshake, Client key exchange (16):
> * TLSv1.2 (OUT), TLS header, Finished (20):
> * TLSv1.2 (OUT), TLS change cipher, Change cipher spec (1):
> * TLSv1.2 (OUT), TLS header, Certificate Status (22):
> * TLSv1.2 (OUT), TLS handshake, Finished (20):
> * TLSv1.2 (IN), TLS header, Finished (20):
> * TLSv1.2 (IN), TLS header, Certificate Status (22):
> * TLSv1.2 (IN), TLS handshake, Finished (20):
> * TLSv1.2 (OUT), TLS header, Supplemental data (23):
> > GET /665e0f93820&uc=10&v=1 HTTP/1.1
> > Host: cdnfhnfile.115.com
> > User-Agent: curl/7.86.0
> > Accept: */*
> > 
> * TLSv1.2 (IN), TLS header, Supplemental data (23):
> < HTTP/1.1 403 Forbidden
> < Server: AliyunOSS
> < Date: Thu, 25 Jul 2024 09:24:17 GMT
> < Content-Type: video/mp4
> < Content-Length: 85
> < Connection: keep-alive
> < Content-Disposition: attachment
> < Timing-Allow-Origin: *
> < x-115-request-id: 66A219C1954D503136EE88E7
> < 
> {"status":403,"message":"invalid signature","request_id":"66A219C1954D503136EE88E7"}
> ```
> 
> 这估计就是emby无法播放的原因。。 但是这个问题不是每次都发生，有时候115 cdn是好的，有时候就会403 感觉是alist的问题。

我试过很多遍，都是403错误，只有刚开始的时候成功过，后来都不行了。

**Comment by stiffme** [comment]
我也是这个情况。
我的ali2115.txt里面的cookie使用的是浏览器的cookie，我用token似乎不行

**Comment by zhengsun2020** [comment]
我这里也是这样的，不带115就没问题，而 115获得的连接总是 403 （但是emby中如果开了转码 就用ffprobe读取并转就没问题了）所以这个可能是 Emby的问题，115 有些什么规范 Emby访问的时候没有遵守或者啥

    Command line: /opt/emby-server/system/EmbyServer.dll -programdata /var/lib/emby -ffdetect /opt/emby-server/bin/ffdetect -ffmpeg /opt/emby-server/bin/ffmpeg -ffprobe /opt/emby-server/bin/ffprobe -restartexitcode 3 -updatepackage emby-server-deb_{version}_arm64.deb
    Operating system: Linux version 5.4.0-135-generic (buildd@bos02-arm64-072) (gcc version 9.4.0 (Ubuntu 9.4.0-1ubuntu1~20.04.1)) #152-Ubuntu SMP Wed Nov 23 20:19:17 UTC 2
    Framework: .NET 6.0.14
    OS/Process: arm64/arm64
    Runtime: opt/emby-server/system/System.Private.CoreLib.dll
    Processor count: 4
    Data path: /var/lib/emby
    Application path: /opt/emby-server/system
    MediaBrowser.Model.Net.HttpException: MediaBrowser.Model.Net.HttpException: _**Forbidden**_
       at Emby.Server.Implementations.HttpClientManager.CoreHttpClientManager.SendAsyncInternal(HttpRequestOptions options, String httpMethod)
       at Emby.Server.Implementations.HttpClientManager.CoreHttpClientManager.SendAsync(HttpRequestOptions options, String httpMethod)
       at Emby.Server.Implementations.HttpServer.HttpResultFactory.GetContent(StaticFileResultOptions options, Int64 offset, Int64 length, CancellationToken cancellationToken)
       at Emby.Server.Implementations.HttpServer.FileWriter.SetContentResponseHeaders(Nullable`1 reportedTotalContentLength, CancellationToken cancellationToken)
       at Emby.Server.Implementations.HttpServer.HttpResultFactory.GetStaticResult(IRequest requestContext, StaticResultOptions options)
       at Emby.Server.MediaEncoding.Api.Progressive.BaseProgressiveStreamingService.ProcessRequest(StreamRequest request, Boolean isHeadRequest)
       at Emby.Server.Implementations.Services.ServiceController.GetTaskResult(Task task)
       at Emby.Server.Implementations.Services.ServiceHandler.ProcessRequestAsync(HttpListenerHost httpHost, IServerApplicationHost appHost, IRequest httpReq, IResponse httpRes, RestPath restPath, String responseContentType, CancellationToken cancellationToken)
       at Emby.Server.Implementations.HttpServer.HttpListenerHost.RequestHandler(IRequest httpReq, ReadOnlyMemory`1 urlString, ReadOnlyMemory`1 localPath, CancellationToken cancellationToken)
    Source: Emby.Server.Implementations
    TargetSite: Void MoveNext()

**Comment by zhsama** [comment]
> 我这里也是这样的，不带115就没问题，而 115获得的连接总是 403 （但是emby中如果开了转码 就用ffprobe读取并转就没问题了）所以这个可能是 Emby的问题，115 有些什么规范 Emby访问的时候没有遵守或者啥
> 
> ```
> Command line: /opt/emby-server/system/EmbyServer.dll -programdata /var/lib/emby -ffdetect /opt/emby-server/bin/ffdetect -ffmpeg /opt/emby-server/bin/ffmpeg -ffprobe /opt/emby-server/bin/ffprobe -restartexitcode 3 -updatepackage emby-server-deb_{version}_arm64.deb
> Operating system: Linux version 5.4.0-135-generic (buildd@bos02-arm64-072) (gcc version 9.4.0 (Ubuntu 9.4.0-1ubuntu1~20.04.1)) #152-Ubuntu SMP Wed Nov 23 20:19:17 UTC 2
> Framework: .NET 6.0.14
> OS/Process: arm64/arm64
> Runtime: opt/emby-server/system/System.Private.CoreLib.dll
> Processor count: 4
> Data path: /var/lib/emby
> Application path: /opt/emby-server/system
> MediaBrowser.Model.Net.HttpException: MediaBrowser.Model.Net.HttpException: _**Forbidden**_
>    at Emby.Server.Implementations.HttpClientManager.CoreHttpClientManager.SendAsyncInternal(HttpRequestOptions options, String httpMethod)
>    at Emby.Server.Implementations.HttpClientManager.CoreHttpClientManager.SendAsync(HttpRequestOptions options, String httpMethod)
>    at Emby.Server.Implementations.HttpServer.HttpResultFactory.GetContent(StaticFileResultOptions options, Int64 offset, Int64 length, CancellationToken cancellationToken)
>    at Emby.Server.Implementations.HttpServer.FileWriter.SetContentResponseHeaders(Nullable`1 reportedTotalContentLength, CancellationToken cancellationToken)
>    at Emby.Server.Implementations.HttpServer.HttpResultFactory.GetStaticResult(IRequest requestContext, StaticResultOptions options)
>    at Emby.Server.MediaEncoding.Api.Progressive.BaseProgressiveStreamingService.ProcessRequest(StreamRequest request, Boolean isHeadRequest)
>    at Emby.Server.Implementations.Services.ServiceController.GetTaskResult(Task task)
>    at Emby.Server.Implementations.Services.ServiceHandler.ProcessRequestAsync(HttpListenerHost httpHost, IServerApplicationHost appHost, IRequest httpReq, IResponse httpRes, RestPath restPath, String responseContentType, CancellationToken cancellationToken)
>    at Emby.Server.Implementations.HttpServer.HttpListenerHost.RequestHandler(IRequest httpReq, ReadOnlyMemory`1 urlString, ReadOnlyMemory`1 localPath, CancellationToken cancellationToken)
> Source: Emby.Server.Implementations
> TargetSite: Void MoveNext()
> ```

请问如何使用ffprobe

**Comment by zhengsun2020** [comment]
Emby如果设置中的用户选项中开着转码权限，用户在用 自带的客户端或者Web观看就会自动转码 转码后就会启用ffprobe读取http连接，就没有问题支持302的115

**Comment by zhsama** [comment]
> Emby如果设置中的用户选项中开着转码权限，用户在用 自带的客户端或者Web观看就会自动转码 转码后就会启用ffprobe读取http连接，就没有问题支持302的115

已开启硬解，且web可以正常播放，但是emby客户端无法播放，就很怪。。。
<img width="829" alt="image" src="https://github.com/user-attachments/assets/ec6f6abe-1cb2-4f78-b4cb-bee76e8c9eb2">

**Comment by zhengsun2020** [comment]
![image](https://github.com/user-attachments/assets/b0d243ce-21c3-45ec-96ae-4d2abd7ae391)
是这个地方

**Comment by jacky940810** [comment]
兄弟们我也遇到同样的问题了，添加了ali2115文件（内容如下）之后emby无法转存到115，我是用几百MB的电视剧测试的，上周还是可以的，是不是有新的风控策略
purge_ali_temp=true
cookie="d5e0692e0dc6dc196e2132fa63ec424dd36dd61f"
purge_pan115_temp=true
dir_id=0
![image](https://github.com/user-attachments/assets/29c85946-26a1-4a61-9921-804137b833b7)

**Comment by jacky940810** [comment]
看了一下日志无法添加115网盘呀
![image](https://github.com/user-attachments/assets/88faac37-30d2-488d-9931-1df71a685896)
但是alist-tvbox是正常的，这可咋办

**Comment by zhengsun2020** [comment]
我没用tvbox的版本，我是原版

**Comment by zhengsun2020** [comment]
换cookie试试

**Comment by jacky940810** [comment]
您说的对 我重启了docker并更换了cookie后修复了该问题

**Comment by zhengsun2020** [comment]
> 兄弟们我也遇到同样的问题了，添加了ali2115文件（内容如下）之后emby无法转存到115，我是用几百MB的电视剧测试的，上周还是可以的，是不是有新的风控策略 purge_ali_temp=true cookie="d5e0692e0dc6dc196e2132fa63ec424dd36dd61f" purge_pan115_temp=true dir_id=0 ![image](https://private-user-images.githubusercontent.com/34416867/353544046-29c85946-26a1-4a61-9921-804137b833b7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI2ODQ2MjEsIm5iZiI6MTcyMjY4NDMyMSwicGF0aCI6Ii8zNDQxNjg2Ny8zNTM1NDQwNDYtMjljODU5NDYtMjZhMS00YTYxLTk5MjEtODA0MTM3YjgzM2I3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODAzVDExMjUyMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThhNzM3YTk4MTg5ZDNlYzM4YzNlZWMzOTlmOTRlM2E0NjZlMzY1YjlhZDJkYzUyMzAzZDA4OTdjOWRmODJiZWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.R7LFkx_0I3mLaui6EY6LWUPzToiBNYY4Iz8l0allYmo)

你这个转存成功了，因为已经之前有过链接，这次就不显示了

**Comment by JacobChen22** [comment]
同样的问题，有人解决了吗？
日志里面是：MediaBrowser.Model.Net.HttpException: Forbidden

**Comment by zhengsun2020** [comment]
解决不了，Emby直接播放（不转码）不支持带着Cookie过去，如果启动了转码就交给了 FFMpeg，就带过去了

**Comment by jokunhe** [comment]
> 换cookie试试

同样的问题，请问更换的是什么模式的cookie ，115的么。  我换了几个版本的cookie都不行

**Comment by jokunhe** [comment]
有解决办法了。 别用6908的端口看 ，用2345的端口  就没有这个问题了

**Comment by zhengsun2020** [comment]
这个我早就发现了，后来我也没继续关注 忘了说了

**Comment by wenshanshan** [comment]
https://www.bilibili.com/video/BV1KtHYeJEw3/

**Comment by wenshanshan** [comment]
老G解决了，看起来是跨域问题

**Comment by zhengsun2020** [comment]
我用反代 直链才可以解决第三方客户端的问题

**Comment by wenshanshan** [comment]
> 我用2345 反代 直链才可以解决第三方客户端的问题

是自带的2345端口？还是自己做了个反代？

**Comment by wenshanshan** [comment]
> 有解决办法了。 别用6908的端口看 ，用2345的端口 就没有这个问题了

试了自带的2345端口，还是不行，播放器是vidhub，报错跟楼主一样，网页版没问题

**Comment by zhengsun2020** [comment]
我用的 potplayer 在PC上可以，在手机上用Emby自己的客户端没问题

**Comment by wenshanshan** [comment]
我重装了小雅和emby，用2345端口，播放器vidhub
阿里转115播放没问题了
